version: '3.5'

services:
  pokeapi:
    container_name: pokeapi
    restart: always
    environment:
      - PORT=8050
      - DB_DATA=
      - ADMIN_USER = 
      - ADMIN_PASS = 
    build: .
    ports:
      - "8000:8050"
    links:
      - mongo
    volumes:
      - .:/app
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  